language: node_js
node_js:
  - '8'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run-script build
after_script: greenkeeper-lockfile-upload
before_deploy:
  - openssl aes-256-cbc -K $encrypted_eab34e191d54_key -iv $encrypted_eab34e191d54_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - npm run-script ci:build
deploy:
  # Fix broken deployment due to
  # https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
cache:
  directories:
    - node_modules
