language: node_js
node_js:
  - "8"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run-script build
after_script: greenkeeper-lockfile-upload

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master

cache:
  directories:
    - node_modules
