language: node_js
node_js:
  - '8'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run-script build
after_script: greenkeeper-lockfile-upload
before_deploy:
  - openssl aes-256-cbc -K $encrypted_92a5b1b18fab_key -iv $encrypted_92a5b1b18fab_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - npm run-script ci:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
cache:
  directories:
    - node_modules
